Fix compilaction error after version bump
```
8.251 /usr/x86_64-hadron-linux-musl/bin/ld: /tmp/ccFkKBkM.ltrans0.ltrans.o: in function `unexportfs_parsed':
8.251 <artificial>:(.text.unexportfs_parsed+0x285): undefined reference to `nfsd_nl_cmd_str'
8.253 collect2: error: ld returned 1 exit status
```

This is also in the `main` branch. Only surfaced here because we fixed
the builds and they go further, eventually hitting this problem.

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>